accounts:
  - name: alice
    coins: ["1000000000000000000000silk"]
  - name: bob
    coins: ["1000000000000000000000silk"]
validator:
  name: alice
  staked: "10000000000000000000silk"

host:
  rpc: ":26657"
  p2p: ":26656"
  prof: ":6060"
  grpc: ":9090"
  api: ":1317"

init:
  home: "/tmp/wasmd"
  keyring-backend: "test"
  config:
    consensus.timeout_commit: "5s"
    consensus.create_empty_blocks_interval: "5s"
  app:
    minimum-gas-prices: "5000000000silk"
    api.enable: true

genesis:
  app_state:
    staking:
      params:
        bond_denom: "silk"
    mint:
      params:
        mint_denom: "silk"
    gov:
      deposit_params:
        max_deposit_period: "172800s"
        min_deposit:
          - amount: "10000000"
            denom: "silk"
      deposits: []
      proposals: []
    crisis:
      constant_fee:
        denom: "silk"
        amount: "1000"
    distribution:
      params:
        community_tax: "0.020000000000000000"
        base_proposer_reward: "0.010000000000000000"
        bonus_proposer_reward: "0.040000000000000000"
        withdraw_addr_enabled: true

build:
  binary: wasmd
  main: ./cmd/wasmd
